include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Custom lint rules
    - avoid_print
    - prefer_const_constructors

analyzer:
  errors:
    # Customize errors and warnings
    unused_import: warning
    dead_code: ignore