name: botika_va
description: A new Flutter plugin of botika Virtual Avatar
version: 0.1.1
homepage: https://github.com/mobiledevbotika/botika_va
repository: https://github.com/mobiledevbotika/botika_va
issue_tracker: https://github.com/mobiledevbotika/botika_va/issues

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_client_sse: ^2.0.0
  http: ^0.13.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^0.1.3

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: online.botika.va
        pluginClass: BotikaVaPlugin
