name: botika_va
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  video_player: 2.7.0
  flutter_client_sse: ^2.0.0
  speech_to_text: ^5.6.1
  dio: ^5.3.3
  geolocator: ^11.0.0
  location: ^5.0.0
  permission_handler: ^10.4.3
  device_info_plus: 3.2.0
  http: ^0.13.5
  uuid: ^4.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.botika_va
        pluginClass: BotikaVaPlugin
